### PR TITLE
Add fastp

### PR DESCRIPTION
**Pull request by mahesh-panchal**
Change Log:
* Added Fastp
* Added optional trimming
* Refactored configuration profiles so updates require minimal changes.

### CODE REVIEW

**Comment by Juke34** [comment]
I don't know how to use the new options, could you update the help? https://github.com/NBISweden/pipelines-nextflow/tree/add_fastp/pipelines/TranscriptAssembly

**Comment by Juke34** [comment]
does not work 

```
N E X T F L O W  ~  version 19.10.0
Launching `/home/jacda119/git/NBIS/pipelines-nextflow/pipelines/TranscriptAssembly/TranscriptAssembly.nf` [extravagant_lalande] - revision: 3214a0a7aa
Unknown config attribute `trimming_tools` -- check config file: /projects/test/test_nextflow/TranscriptAssembly/stranded/params.config
```

My parameter file contains:
```
params.trimmer = trimming_tools[0]
```

**Comment by mahesh-panchal** [comment]
Well, that is supposed to have a string value that you give. 
I'll change the code so 'fastp' is the default then, rather than the first trimmer in the list of tools.

**Comment by Juke34** [comment]
`Error executing process > 'transcript_assembly:multiqc'`

is the path wrong? 
`params.multiqc_config = "$baseDir/config/multiqc_conf.yml"`

**Comment by mahesh-panchal** [comment]
The path should be correct.

**Pull request merged**
