### PR TITLE
fixed config path for BUSCO when using Singularity

### PR DESCRIPTION
**Pull request by quiestrho**

### CODE REVIEW

**Comment by mahesh-panchal** [comment]
Issues:
* busco exits with exit code 0 on errors.
* `config.ini` path is different in conda, and singularity environments.
  - conda: `$workDir/conda/busco-<somestring>/config/config.ini`
  - singularity:`/usr/local/config/config.ini`
* Busco v4.0.2 config.ini has incorrect script path to `gff2gbSmallDNA.pl` in conda package.
* Conda package Busco v4.0.5 contains numerous package conflicts.

**Comment by quiestrho** [comment]
Resolved issue with BUSCO by migrating to docker hub BUSCO container.

**Comment by mahesh-panchal** [comment]
That doesn't solve the issue when using the conda environments though. I'm thinking of roling back to a previous version of busco.

**Comment by mahesh-panchal** [comment]
Solved config path issue with https://github.com/NBISweden/pipelines-nextflow/pull/11/commits/13d24968be889eddd315ec72437b28e00fd3ba92.

**Comment by mahesh-panchal** [comment]
No issues now using Busco 4.0.2 with either conda, or singularity on the other branch. The `gff2gbSmallDNA.pl` note above seems to be mistake.

**Pull request closed without merging**
