### PR TITLE
Add ability to explore various values of AED and LD.

### LINKED ISSUE #94: Update params.conda to conda.enabled
Nextflow introduced `conda.enabled` in `22.08.0-edge`. Code needs to be updated to reflect that.

### PR DESCRIPTION
**Pull request by mahesh-panchal**
Adds parameters to allow for a parameter sweep across values of AED and locus distance. Closes https://github.com/NBISweden/pipelines-nextflow/issues/57

Changes the `params.enable_conda` to `conda.enabled`. Closes #94

---

Additionally fixes other workflows broken by module updates and other nf-core tweeks.

---

Tests run:
```
nextflow run main.nf -profile test,docker,gitpod --subworkflow 'abinitio_training' -resume  # passes
nextflow run main.nf -profile test,docker,gitpod --subworkflow 'annotation_preprocessing' -resume # passes
nextflow run main.nf -profile test,docker,gitpod --subworkflow 'functional_annotation' -resume # fails: Interproscan is still flaky
nextflow run main.nf -profile test,docker,gitpod --subworkflow 'transcript_assembly' -resume # passes
```

### CODE REVIEW

**Review by LucileSol — APPROVED** [review]

**Comment by LucileSol** [comment]
I have not tested it yet, planning to do that next week.

**Comment by LucileSol** [comment]
The pipeline seems to be splitting the gff file into mrna.gff and trna.gff, four times (I gave it 2 sets of parameters). It would be more efficient/faster
 if it does it only once.

**Comment by LucileSol** [comment]
I got an error message : 

```Error executing process > 'ABINITIO_TRAINING:BLAST_RECURSIVE (codingGeneFeatures.filter.longest_cds.complete.good_distance_proteins)'

Caused by:
  Process `ABINITIO_TRAINING:BLAST_RECURSIVE` input file name collision -- There are multiple input files for each of the following file names: blast_db
```

**Comment by mahesh-panchal** [comment]
Yes, I'm debugging that now. I just updated the test profile.

**Comment by mahesh-panchal** [comment]
😮 All tests pass 🚀

**Comment by mahesh-panchal** [comment]
Going to add summary script too now. https://github.com/NBISweden/annotation-cluster/wiki/Old-Abinitio_pipeline

**Comment by mahesh-panchal** [comment]
All tests pass locally.

**Pull request merged**
