### PR TITLE
Add CITATION.cff

### PR DESCRIPTION
**Pull request by mahesh-panchal**
We've had a request for the citation for the workflow. So I'm doing it properly and adding a citation file and linking it to Zenodo for a doi.  

Who should be on the citation?

### CODE REVIEW

**Comment by Juke34** [comment]
How does it work the .cff? Is it static? You mean Zenodo will reflect only the cff file?
I'm asking because in the other repos I was using only Zenodo, that was automaticaly providing a general DOI for all releases but also an independant DOI for each release.

**Review by Juke34 — APPROVED** [review]
It would not be confusing to use different version between .cff and repo verison? (v1.1.0 vs v.1.0.0)

**Comment by mahesh-panchal** [comment]
I'm trying (unsuccessfully atm) to make a doi for this release via Zenodo.

The Citation CFF file is an extra thing Github just added some new support for to put a citation link on the side of the repo.
https://github.blog/changelog/2021-07-29-enhanced-citation-support/
It let's others pull in the citation in the reference manager of choice.

When a new release is made, the doi needs to be updated in the CFF too.

**Comment by mahesh-panchal** [comment]
@Juke34 Do you want your affiliation on there?

Should Marc or anyone else be on this citation?

**Comment by Juke34** [comment]
Sounds good this .cff, it allows to choose who to add as author in the citation. Zenodo puts anyone which has made a modification. For AGAT I had someone unknown that only corrected a plurial in the README and he is among the co-authors ^^

**Comment by mahesh-panchal** [comment]
Ah, now I understand the confusion part. I need to check. 
If one makes a release, then the CFF has the old doi before Zenodo makes a new one.

**Comment by Juke34** [comment]
> @Juke34 Do you want your affiliation on there?
 I'm not sure what I'm suppose to do... I guess with ORCID it is enough.

> Should Marc or anyone else be on this citation?
It is true that we got inspired by the work he made with Bpipe, so I guess we should.

**Comment by mahesh-panchal** [comment]
> Ah, now I understand the confusion part. I need to check.
> If one makes a release, then the CFF has the old doi before Zenodo makes a new one.

I think the current solution to this is to just not include the doi here and just add the doi badge instead.

**Comment by mahesh-panchal** [comment]
OK. Decided to put Marc in an acknowledgement instead.

**Review by Juke34 — APPROVED** [review]

**Review by LucileSol — APPROVED** [review]

**Pull request merged**
